import{a as S,i as q,A as H}from"./assets/vendor-BOf7_0lP.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const n of document.querySelectorAll('link[rel="modulepreload"]'))r(n);new MutationObserver(n=>{for(const s of n)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function o(n){const s={};return n.integrity&&(s.integrity=n.integrity),n.referrerPolicy&&(s.referrerPolicy=n.referrerPolicy),n.crossOrigin==="use-credentials"?s.credentials="include":n.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(n){if(n.ep)return;n.ep=!0;const s=o(n);fetch(n.href,s)}})();const E=document.querySelector(".loader-more"),M=document.querySelector(".loader-more-container"),C=document.querySelector(".furniture-list"),k=document.querySelector(".load-more-btn");let a=1,l=null;const L=8;window.allFurnitures=window.allFurnitures||[];async function j(){try{const t=(await S("https://furniture-store.b.goit.study/api/categories")).data;t.unshift({_id:"0",name:"Всі товари"}),document.querySelectorAll(".category-card").forEach((r,n)=>{const s=t[n];if(!s)return;r.dataset.id=s._id;const i=r.querySelector(".category-title");i&&(i.textContent=s.name)})}catch{q.show({message:"Sorry, something went wrong. Please try again!",position:"topRight",messageColor:"#fff",titleColor:"#fff",color:"#ef4040",iconUrl:"../images/our-furniture/bi_x-octagon-2.svg",maxWidth:432})}}async function u(e=1,t){try{R(),b();let o=`https://furniture-store.b.goit.study/api/furnitures?limit=${L}&page=${e}`;t&&t!=="0"&&(o+=`&category=${t}`);const n=(await S(o)).data;z(n),l===null&&(l=Math.ceil(n.totalItems/L)),e>=l?b():W()}catch{q.show({message:"Sorry, something went wrong. Please try again!",position:"topRight",messageColor:"#fff",titleColor:"#fff",color:"#ef4040",iconUrl:"../images/our-furniture/bi_x-octagon-2.svg",maxWidth:432})}finally{U()}}function z(e){const t=e.furnitures;window.allFurnitures=[...new Map([...window.allFurnitures,...t].map(r=>[r._id,r])).values()];const o=t.map(r=>{const{_id:n,name:s,description:i,price:B,images:I}=r;return`
    <li class="furniture-card" id="${n}"> 
  <img src="${I[0]}" alt="${i}" class="furniture-image" />
      <p class="furniture-name">${s}</p>
      <div class="color-wrap">
        <span class="grey-color"></span>
        <span class="beige-color"></span>
        <span class="black-color"></span>
      </div>
      <p class="furniture-price">${B} грн</p>
  <button class="details-btn" type="button">Детальніше</button>
</li>`}).join("");C.insertAdjacentHTML("beforeend",o)}async function D(e){const t=e.target.closest(".category-card");if(!t)return;document.querySelectorAll(".category-card.active").forEach(r=>r.classList.remove("active")),t.classList.add("active");const o=t.dataset.id;G(),a=1,o==="0"?(l=null,u(a)):(l=null,u(a,o))}function N(){a+=1,u(a)}function R(){E.classList.remove("hidden"),M.style.display="flex"}function U(){E.classList.add("hidden"),M.style.display="none"}function W(){k.classList.remove("hidden")}function b(){k.classList.add("hidden")}function G(){C.innerHTML="",window.allFurnitures=[]}const K=document.querySelector(".categories-list"),V=document.querySelector(".load-more-btn");V.addEventListener("click",N);K.addEventListener("click",D);j();u(a);const v=document.querySelector("[data-menu]"),$=document.querySelector("[data-menu-open]"),J=document.querySelector("[data-menu-close]"),Q=document.querySelectorAll(".mobile-nav-list a, .mobile-btn");function X(){v.classList.add("is-open"),document.body.style.overflow="hidden",document.addEventListener("keydown",x),document.addEventListener("click",_)}function y(){v.classList.remove("is-open"),document.body.style.overflow="",document.removeEventListener("keydown",x),document.removeEventListener("click",_)}function x(e){e.key==="Escape"&&y()}function _(e){!v.contains(e.target)&&!$.contains(e.target)&&y()}$.addEventListener("click",X);J.addEventListener("click",y);Q.forEach(e=>{e.addEventListener("click",t=>{t.preventDefault();const o=e.getAttribute("href"),r=document.querySelector(o);r&&(y(),r.scrollIntoView({behavior:"smooth"}))})});function Y(){document.addEventListener("DOMContentLoaded",()=>{new H(".accordion",{duration:300,showMultiple:!1}).open(0)})}Y();const m=document.querySelector(".modal"),A=document.querySelector(".modal_close"),w=document.querySelector(".modal_main-image img"),P=document.querySelector(".modal_title"),Z=document.querySelector(".modal_category"),ee=document.querySelector(".modal_price"),te=document.querySelector(".modal_description"),p=document.querySelector(".modal_rate"),h=document.querySelector(".color-checkboxes"),oe=document.querySelector(".modal_sizes"),c=document.querySelector(".modal_order-btn"),O=document.querySelector(".modal_thumbnails"),ne=document.querySelector(".furniture-list");let f=0,d=[];function F(e){e.key==="Escape"&&g()}function T(){if(!d.length)return;w.src=d[f],w.alt=P.textContent||"Фото товару";const e=d.map((t,o)=>({src:t,i:o})).filter(({i:t})=>t!==f).map(({src:t,i:o})=>`
      <img class="thumbnail-img" src="${t}" alt="thumb ${o}" data-index="${o}">
    `).join("");O.innerHTML=e}O?.addEventListener("click",e=>{const t=e.target.closest(".thumbnail-img");t&&(f=Number(t.dataset.index),T())});ne?.addEventListener("click",e=>{const t=e.target.closest(".details-btn");if(!t)return;const o=t.closest(".furniture-card");if(!o)return;const r=o.dataset.id||o.id;if(!r||!window.allFurnitures)return;const n=window.allFurnitures.find(s=>s._id===r);n&&re(n)});function re(e){if(P.textContent=e.name||"Без назви",Z.textContent=e.type||"Тип невідомий",ee.textContent=`${e.price} грн`||"Ціна невідома",te.textContent=e.description||"Опис відсутній",c.dataset.model=e.name||"",c.setAttribute("data-modal-open",""),c.setAttribute("data-id",e._id),c.setAttribute("data-marker","product-modal"),p&&typeof e.rate=="number"){const t=Math.round(e.rate*10)/10,o=Math.min(5,t)/5*100;p.innerHTML=`
      <div class="star-rating" style="--star-fill: ${o}%"></div>
      <span class="rating-text">${t.toFixed(1)}</span>
    `}else p.innerHTML="";h&&Array.isArray(e.color)?h.innerHTML=e.color.map((t,o)=>{const r=`color-${o}`;return`
          <input type="radio" id="${r}" name="color" data-color="${t}" ${o===0?"checked":""} />
          <label for="${r}" style="background-color: ${t}"></label>
        `}).join(""):h.innerHTML="",oe.textContent=`Розміри: ${e.sizes||"невідомі"}`,d=Array.isArray(e.images)?e.images.slice():[],f=0,T(),c.dataset.id=e._id||"",m.classList.remove("visually-hidden"),A.focus(),document.body.style.overflow="hidden",document.addEventListener("keydown",F)}function g(){m.classList.add("visually-hidden"),document.body.style.overflow="",document.removeEventListener("keydown",F)}A?.addEventListener("click",g);m?.addEventListener("click",e=>{e.target===m&&g()});c.addEventListener("click",()=>{const e=document.querySelector('.color-checkboxes input[type="radio"]:checked'),t=e?e.dataset.color:null;t&&c.setAttribute("data-color",t),c.dataset.model&&c.setAttribute("data-model",c.dataset.model),g();const o=new CustomEvent("open-order-modal",{detail:{model:c.dataset.model||"",color:t}});document.dispatchEvent(o)});
//# sourceMappingURL=index.js.map
